trigger:
  - main

variables:
  - group: dev-databricksCICD
  - group: uat-databricksCICD
  - group: prod-databricksCICD

  - name: vmImageName
    value: "windows-latest"
  - name: notebooksPath
    value: "Notebooks"
  - name: bicepPath
    value: "CICD/bicep"

pool:
  vmImage: $(vmImageName)


stages:
  # DEV Environment - Infrastructure Deployment
  - template: templates/deploy-bicep.yml
    parameters:
      stageId: "Deploy_to_Dev_Infrastructure"
      env: "dev"
      environmentName: $(dev-environment-name)
      resourceGroupName: $(dev-resource-group-name)
      serviceConnection: $(dev-service-connection-name)
      bicepPath: $(bicepPath)
      parametersFile: "dev.parameters.json"

  # DEV Environment - Notebook Deployment
  - template: templates/deploy-notebooks.yml
    parameters:
      dependsOn: [ "Deploy_to_Dev_Infrastructure" ]
      stageId: "Deploy_to_Dev_Environment"
      env: "dev"
      environmentName: $(dev-environment-name)
      resourceGroupName: $(dev-resource-group-name)
      serviceConnection: $(dev-service-connection-name)
      notebooksPath: $(notebooksPath)

  # UAT Environment - Infrastructure Deployment  
  - template: templates/deploy-bicep.yml
    parameters:
      dependsOn: [ "Deploy_to_Dev_Environment" ]
      stageId: "Deploy_to_UAT_Infrastructure"
      env: "uat"
      environmentName: $(uat-environment-name)
      resourceGroupName: $(uat-resource-group-name)
      serviceConnection: $(uat-service-connection-name)
      bicepPath: $(bicepPath)
      parametersFile: "uat.parameters.json"

  # UAT Environment - Notebook Deployment
  - template: templates/deploy-notebooks.yml
    parameters:
      dependsOn: [ "Deploy_to_UAT_Infrastructure" ]
      stageId: "Deploy_to_UAT_Environment"
      env: "uat"
      environmentName: $(uat-environment-name)
      resourceGroupName: $(uat-resource-group-name)
      serviceConnection: $(uat-service-connection-name)
      notebooksPath: $(notebooksPath)

  # PROD Environment - Infrastructure Deployment
  - template: templates/deploy-bicep.yml
    parameters:
      dependsOn: [ "Deploy_to_UAT_Environment" ]
      stageId: "Deploy_to_PROD_Infrastructure"
      env: "prod"
      environmentName: $(prod-environment-name)
      resourceGroupName: $(prod-resource-group-name)
      serviceConnection: $(prod-service-connection-name)
      bicepPath: $(bicepPath)
      parametersFile: "prod.parameters.json"

  # PROD Environment - Notebook Deployment
  - template: templates/deploy-notebooks.yml
    parameters:
      dependsOn: [ "Deploy_to_PROD_Infrastructure" ]
      stageId: "Deploy_to_PROD_Environment"
      env: "prod"
      environmentName: $(prod-environment-name)
      resourceGroupName: $(prod-resource-group-name)
      serviceConnection: $(prod-service-connection-name)
      notebooksPath: $(notebooksPath)
